[package]

name = "maud"
# When releasing a new version, please update html_root_url in src/lib.rs
version = "0.17.2"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/maud/"
homepage = "https://maud.lambda.xyz/"
repository = "https://github.com/lfairy/maud"
description = "Compile-time HTML templates."
categories = ["template-engine"]

[dependencies]
maud_htmlescape = { version = "0.17.0", path = "../maud_htmlescape" }
maud_macros = { version = "0.17.2", path = "../maud_macros" }
iron = { version = ">= 0.5.1, < 0.7.0", optional = true }
rocket = { git = "https://github.com/SergioBenitez/Rocket", optional = true }

[dev-dependencies]
maud_lints = { version = "0.17.0", path = "../maud_lints" }

[badges]
travis-ci = { repository = "lfairy/maud" }

[package.metadata.docs.rs]
all-features = true
